version: '3.8'
services:
  refserver:
    build: .
    container_name: refserver
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=host.docker.internal:11434
      - HURIDOCS_LAYOUT_URL=http://huridocs-layout:5000
    depends_on:
      - huridocs-layout
    extra_hosts:
      - "host.docker.internal:host-gateway"

  huridocs-layout:
    image: huridocs/pdf-document-layout-analysis:latest
    container_name: huridocs-layout
    ports:
      - "5000:5000"
    environment:
      - WORKERS=2 