# CPU-only configuration for RefServer
# Usage: docker-compose -f docker-compose.cpu.yml up
# 
# Prerequisites:
# - Run external Ollama with Llama 3.2: ollama run llama3.2
# 
# This configuration disables GPU-dependent services:
# - LLaVA (OCR quality assessment) - requires GPU for image processing
# - Huridocs (Layout analysis) - GPU accelerated
#
# Core functionality that works on CPU:
# - PDF OCR processing (Tesseract)
# - Text extraction and embeddings (BGE-M3)
# - Metadata extraction (Llama 3.2 via external Ollama)
# - Admin interface

services:
  refserver:
    build: .
    container_name: refserver-cpu
    ports:
      - "8060:8000"
    volumes:
      - ./refdata:/refdata
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=host.docker.internal:11434  # Use external Ollama for Llama 3.2 metadata extraction
      - HURIDOCS_LAYOUT_URL=disabled  # Disable Huridocs layout analysis (GPU accelerated)
      - LLAVA_ENABLED=false  # Disable LLaVA OCR quality assessment (GPU required)
      - CPU_ONLY_MODE=true
      - LOG_LEVEL=INFO
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped