services:
  refserver:
    image: honestjung/refserver:latest  # Docker Hub에서 가져오기
    container_name: refserver
    ports:
      - "8060:8000"
    volumes:
      - ./refdata:/refdata
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=host.docker.internal:11434
      - HURIDOCS_LAYOUT_URL=http://huridocs-layout:5060
    depends_on:
      - huridocs-layout
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  huridocs-layout:
    image: honestjung/pdf-layout-custom:latest
    container_name: huridocs-layout
    ports:
      - "8061:5060"  # Map external 8061 to internal 5060
    environment:
      - WORKERS=2
    restart: unless-stopped