services:
  refserver:
    build: .
    container_name: refserver
    ports:
      - "8060:8000"
    volumes:
      - ./refdata:/refdata
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=host.docker.internal:11434
      - HURIDOCS_LAYOUT_URL=http://huridocs-layout:5060
      - ENABLE_GPU_INTENSIVE_TASKS=true  # Set to false to skip GPU tasks
    depends_on:
      - huridocs-layout
    extra_hosts:
      - "host.docker.internal:host-gateway"

  huridocs-layout:
    #image: huridocs/pdf-document-layout-analysis:v0.0.23
    image: honestjung/pdf-layout-custom:latest # model files included in the docker image
    container_name: huridocs-layout
    ports:
      - "8061:5060"  # Map external 8061 to internal 5060
    environment:
      - WORKERS=2 