version: '3.8'
services:
  refserver:
    build: ./app
    container_name: refserver
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./data:/data
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1 