# CPU-only configuration for RefServer
# Usage: docker-compose -f docker-compose.cpu.yml up
# 
# Prerequisites:
# - Run external Ollama with Llama 3.2: ollama run llama3.2
# 
# This configuration disables GPU-dependent services:
# - LLaVA (OCR quality assessment) - requires GPU for image processing
# - Huridocs (Layout analysis) - GPU accelerated
#
# Core functionality that works on CPU:
# - PDF OCR processing (Tesseract)
# - Text extraction and embeddings (BGE-M3)
# - Metadata extraction (Llama 3.2 via external Ollama)
# - Admin interface

services:
  refserver:
    # For local development (build from source):
    build: .
    # For production (use Docker Hub image):
    # image: honestjung/refserver:latest
    container_name: refserver-cpu
    ports:
      - "8060:8000"
    volumes:
      - ./refdata:/refdata
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_HOST=host.docker.internal:11434  # Use external Ollama for Llama 3.2 metadata extraction
      - HURIDOCS_LAYOUT_URL=http://huridocs-layout:5060  # Enable Huridocs layout analysis for testing
      - LLAVA_ENABLED=false  # Disable LLaVA OCR quality assessment (GPU required)
      - CPU_ONLY_MODE=true
      - LOG_LEVEL=INFO
      - ENABLE_QUARANTINE=false  # Disable file quarantine for development
      - MAX_FILE_SIZE=200000000  # 200MB file size limit
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    depends_on:
      - huridocs-layout

  huridocs-layout:
    image: huridocs/pdf-document-layout-analysis:1.8.8
    container_name: huridocs-layout
    ports:
      - "8061:5060"
    environment:
      - WORKERS=1  # Reduce workers to save memory
      - TIMEOUT=600
      - WORKER_CLASS=sync
      - WORKER_CONNECTIONS=1
      - MAX_REQUESTS=100
      - MAX_REQUESTS_JITTER=10
      - PRELOAD_APP=true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G  # Set memory limit
        reservations:
          memory: 2G  # Reserve minimum memory